# Default values for datacatalog-frontend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

environment: test
appName: datacatalog-frontend

deployment:
  replicaCount: 1

  image:
    repository: datacatalog-frontend
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"

  livenessProbe:
    path: /health
    initialDelaySeconds: 30
    timeoutSeconds: 2
    periodSeconds: 60

  dynamicEnvironment:
    baseHref: '/'
    base: https://localhost:5000
    production: false
    oidcSettings:
      client_id: interactive.public
      authority: https://demo.identityserver.io/
      response_type: code
      post_logout_redirect_uri: http://localhost:4200/
      loadUserInfo: false
      redirect_uri: http://localhost:4200/login
      silent_redirect_uri: http://localhost:4200/login
      automaticSilentRenew: true
      scope: openid profile offline_access

  podSecurityContext: {}

  securityContext: {}

  annotations: {}

  autoscaling:
    enabled: false

  resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    kubernetes.io/ingress.class: nginx
  
  host: "dp-test.com"
  path: "/"

  # tls: 
  #   hosts:
  #     - secretName: datacatalog-energinet-crt
  #       hosts:
  #         - dataplatform.energinet.dk
      
externalSecret:
  enable: false