parameters:

  # Specifies if the application should be deployed to the dev environment (and thus not to test, preprod and prod)
  - name: deployToDev
    displayName: Deploy to Dev environment
    type: boolean
    default: false

  # The postfix name of the dev environment (typically the initials of a developer)
  - name: devEnvironmentName
    displayName: Dev environment name (typically user initials)
    default: dev
    type: string

trigger:
- master

variables:

  # Name of the App Service to host the application
  appServiceName: dpdatacatalogwebapp-appservice

  # If it is NOT a pull request build and we're building the 'master' branch OR it's a manual build - we should deploy the changes
  ${{ if or(and(ne(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.SourceBranch'], 'refs/heads/master')), eq(variables['Build.Reason'], 'Manual')) }}:
    deployChanges: true

  # If the above condition isn't met, we should NOT deploy the changes
  ${{ if not(or(and(ne(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.SourceBranch'], 'refs/heads/master')), eq(variables['Build.Reason'], 'Manual'))) }}:
    deployChanges: false

resources:
  repositories:
    - repository: Infrastructure.Pipelines
      type: git
      name: Infrastructure.Pipelines

stages:
- template: node/angular-app/default-angular-pipeline.yml@Infrastructure.Pipelines
  parameters:
    deployToDev: ${{ parameters.deployToDev }}
    devEnvironmentName: ${{ parameters.devEnvironmentName }}
    deployChanges: ${{ variables.deployChanges }}
    appServiceName: ${{ variables.appServiceName }}